version: '3'

services:
  python:
    container_name: raiden
    build: .
    restart: unless-stopped
    environment:
      - WBHOOK_URL=https://cloud.deesiigneer.ru/webhook/
      - BOT_TOKEN=${{ secrets.BOT_TOKEN }}
      - SP_CARD_ID=${{ secrets.SP_CARD_ID }}
      - SP_TOKEN=${{ secrets.SP_TOKEN }}
